// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package dev.gene.editor

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object EditorApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * A span of the source recording to keep, in milliseconds.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class KeepRange (
  val startMs: Long,
  val endMs: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KeepRange {
      val startMs = pigeonVar_list[0] as Long
      val endMs = pigeonVar_list[1] as Long
      return KeepRange(startMs, endMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      startMs,
      endMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as KeepRange
    return EditorApiPigeonUtils.deepEquals(this.startMs, other.startMs) && EditorApiPigeonUtils.deepEquals(this.endMs, other.endMs)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + EditorApiPigeonUtils.deepHash(this.startMs)
    result = 31 * result + EditorApiPigeonUtils.deepHash(this.endMs)
    return result
  }
}

/**
 * The outcome of analyzing a recording's audio for dead air.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class DetectionResult (
  /** Speech spans to retain, in order. */
  val ranges: List<KeepRange?>,
  /** Duration of the original recording (ms). */
  val originalMs: Long,
  /** Total duration retained after trimming (ms). */
  val keptMs: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DetectionResult {
      val ranges = pigeonVar_list[0] as List<KeepRange?>
      val originalMs = pigeonVar_list[1] as Long
      val keptMs = pigeonVar_list[2] as Long
      return DetectionResult(ranges, originalMs, keptMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      ranges,
      originalMs,
      keptMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as DetectionResult
    return EditorApiPigeonUtils.deepEquals(this.ranges, other.ranges) && EditorApiPigeonUtils.deepEquals(this.originalMs, other.originalMs) && EditorApiPigeonUtils.deepEquals(this.keptMs, other.keptMs)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + EditorApiPigeonUtils.deepHash(this.ranges)
    result = 31 * result + EditorApiPigeonUtils.deepHash(this.originalMs)
    result = 31 * result + EditorApiPigeonUtils.deepHash(this.keptMs)
    return result
  }
}
private open class EditorApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KeepRange.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DetectionResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is KeepRange -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is DetectionResult -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * On-device video editor, implemented natively (Android: MediaCodec + Media3).
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface EditorApi {
  /**
   * Analyzes [inputPath]'s audio and returns the speech keep-ranges,
   * trimming dead air and collapsing long pauses.
   */
  fun detectKeepRanges(inputPath: String, callback: (Result<DetectionResult>) -> Unit)
  /**
   * Clips [inputPath] to [keepRanges], concatenates the kept spans, and
   * writes a single mp4 to [outputPath]. Returns the output path.
   */
  fun tighten(inputPath: String, keepRanges: List<KeepRange?>, outputPath: String, callback: (Result<String>) -> Unit)

  companion object {
    /** The codec used by EditorApi. */
    val codec: MessageCodec<Any?> by lazy {
      EditorApiPigeonCodec()
    }
    /** Sets up an instance of `EditorApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: EditorApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.gene.EditorApi.detectKeepRanges$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val inputPathArg = args[0] as String
            api.detectKeepRanges(inputPathArg) { result: Result<DetectionResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(EditorApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(EditorApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.gene.EditorApi.tighten$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val inputPathArg = args[0] as String
            val keepRangesArg = args[1] as List<KeepRange?>
            val outputPathArg = args[2] as String
            api.tighten(inputPathArg, keepRangesArg, outputPathArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(EditorApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(EditorApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
